name: deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  SYSTEM_NAME: vacca-note
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Deploay view to Fargate
    
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🚀start deploy ${{env.AWS_REGION}}"
      
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3

      - name: Package Install
        run: yarn install

      - name: Build
        run: CI=false yarn build

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1800
      
      - name: Deploy to S3
        run: |
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --recursive
        
      - name: Invalidation to cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


